<?php
/**
 * REST API Controller for handling booking endpoints.
 */

if ( ! defined( 'WPINC' ) ) {
	die;
}

class FMR_Booking_REST_Controller {

	private $availability_service;
	private $booking_service;

	public function __construct( FMR_Availability_Service $availability_service, FMR_Booking_Service $booking_service ) {
		$this->availability_service = $availability_service;
		$this->booking_service      = $booking_service;
	}

	public function register_routes() {
		$namespace = 'fmr-booking/v1';

		register_rest_route( $namespace, '/slots', array(
			'methods'             => WP_REST_Server::READABLE,
			'callback'            => array( $this, 'get_slots' ),
			'permission_callback' => '__return_true', // Publicly accessible
		) );

		register_rest_route( $namespace, '/book', array(
			'methods'             => WP_REST_Server::CREATABLE,
			'callback'            => array( $this, 'create_booking' ),
			'permission_callback' => '__return_true', // Publicly accessible
		) );
	}

	public function get_slots( WP_REST_Request $request ) {
		$service_id = $request->get_param( 'service_id' );
		$date       = $request->get_param( 'date' );

		if ( empty( $service_id ) || empty( $date ) ) {
			return new WP_Error( 'missing_params', 'Service ID and Date are required.', array( 'status' => 400 ) );
		}

		try {
			$slots = $this->availability_service->get_available_slots( absint( $service_id ), sanitize_text_field( $date ) );
			return rest_ensure_response( $slots );
		} catch ( Exception $e ) {
			// 🚨 FIX: Return the actual error message generated by the Availability Engine!
			return new WP_Error( 'availability_error', $e->getMessage(), array( 'status' => 500 ) );
		}
	}

	public function create_booking( WP_REST_Request $request ) {
		$params = $request->get_json_params();

		try {
			$appointment = $this->booking_service->create_appointment( $params );
			return rest_ensure_response( array(
				'success' => true,
				'message' => __( 'Booking successfully created.', 'fmr-booking' ),
				'data'    => $appointment,
			) );
		} catch ( Exception $e ) {
			return new WP_Error( 'booking_error', $e->getMessage(), array( 'status' => 400 ) );
		}
	}
}
